apiVersion: batch/v1
kind: Job
metadata:
  name: uvicorn-pytest-job
  labels:
    env: dev
    region: us-west
spec:
  template:
    spec:
      containers:
      - name: uvicorn-pytest
        image: nguntupalli/uvicorn-pytest:1
        ports:
        - containerPort: 8000
      restartPolicy: Never
  backoffLimit: 4
